const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={step:1,category:null,level:'Beginner',resultText:''};
const categoryGrid=$('#categoryGrid');
function renderCategories(filter=''){
 categoryGrid.innerHTML=''; CATEGORIES.forEach((c,i)=>{if(!(`${c[1]} ${c[2]}`.toLowerCase().includes(filter.toLowerCase())))return; const b=document.createElement('button');b.className='category-card'+(state.category?.[1]===c[1]?' selected':'');b.innerHTML=`<strong>${c[0]} ${c[1]}</strong><small>${c[2]}</small>`;b.onclick=()=>{state.category=c; renderCategories($('#categorySearch').value); fillTypes();};categoryGrid.appendChild(b);});
}
function fillTypes(){const sel=$('#projectType');sel.innerHTML=(PROJECT_TYPES[state.category?.[1]]||['Custom Project']).map(x=>`<option>${x}</option>`).join('');}
function goStep(n){state.step=n;$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n));$('#stepLabel').textContent=`Step ${n} of 4`;$(`#progressBar`).style.width=(n*25)+'%';$('#prevBtn').style.visibility=n===1?'hidden':'visible';$('#nextBtn').textContent=n===4?'Generate Project Kit →':'Continue →';updatePreview();}
function updatePreview(){if(state.category){$('#previewCategory').textContent=state.category[0]+' '+state.category[1];$('#previewName').textContent=$('#projectName').value||'Your project';$('#previewDesc').textContent=$('#goal').value||state.category[2];}}
function validate(){if(state.step===1&&!state.category){alert('Please choose a category.');return false}if(state.step===2&&!$('#projectName').value.trim()){alert('Please enter a project name.');return false}if(state.step===3&&!$('#goal').value.trim()){alert('Please describe your project.');return false}return true}
function promptFor(title, body){return `You are an expert ${state.category[1]} project consultant.\n\nPROJECT: ${$('#projectName').value}\nPROJECT TYPE: ${$('#projectType').value}\nEXPERIENCE: ${state.level}\nTECHNOLOGY/PLATFORM: ${$('#technology').value||'Not specified'}\nPURPOSE: ${$('#purpose').value}\nPROJECT CONTEXT: ${$('#goal').value}\n\nTASK: ${body}\n\nREQUIREMENTS:\n- Be practical and step-by-step.\n- Do not invent missing facts; clearly mark assumptions.\n- Tailor the response to the project context and experience level.\n- Use clear headings, tables, checklists, or code blocks where useful.\n- End with a short “Next Step” section.\n- If professional verification is required, identify what should be reviewed by a qualified professional.`}
function generate(){
 const checks=$$('.check-grid input:checked').map(x=>x.value), name=$('#projectName').value.trim(), cat=state.category;
 $('#resultTitle').textContent=name;$('#resultMeta').textContent=`${cat[0]} ${cat[1]} • ${$('#projectType').value} • ${state.level}`;
 let html='', text=`AI PROJECT COPILOT\n${name}\n${cat[1]} • ${$('#projectType').value}\n\n`;
 if(checks.includes('brief')){let content=`Create a complete project brief for the project described above. Include: executive summary, problem, target users, goals, features, scope, assumptions, required resources, risks, success criteria, and a clear definition of done.`;html+=block('Project Brief',promptFor('Project Brief',content),'');text+='PROJECT BRIEF PROMPT\n'+promptFor('',content)+'\n\n';}
 if(checks.includes('roadmap')){const phases=['Discovery & Research','Requirements & Scope','Planning & Architecture','Design & Content','Build / Execute','Review & Improvement','Testing & Quality Control','Launch / Deployment','Documentation & Maintenance'];html+=`<div class="result-block"><div class="block-head"><h3>🗺️ Project Roadmap</h3></div><div class="block-body"><div class="roadmap">${phases.map((p,i)=>`<div class="road-step"><span class="road-num">${i+1}</span><div><b>${p}</b><p>Complete this phase, document the result, then use it as input for the next phase.</p></div></div>`).join('')}</div></div></div>`;text+='ROADMAP\n'+phases.map((p,i)=>`${i+1}. ${p}`).join('\n')+'\n\n';}
 if(checks.includes('prompts')){const prompts=[['Research & Discovery','Research the problem, target audience, user needs, existing solutions, constraints, assumptions, and project opportunities.'],['Requirements','Convert the project context into functional requirements, non-functional requirements, user stories, acceptance criteria, and a prioritized MVP scope.'],['Plan & Architecture','Create a practical architecture, workflow, tools, file/document structure, dependencies, milestones, and implementation sequence appropriate for this project.'],['Build / Execute','Create a step-by-step implementation plan. Work in small verifiable stages. For technical projects, provide files and code only when the relevant requirements are clear.'],['Review & Improve','Review the current project output against the requirements. Identify missing pieces, inconsistencies, usability issues, and concrete improvements.'],['Testing & QA','Create a testing plan with functional, edge-case, usability, security, performance, and compatibility checks relevant to this project.'],['Launch / Delivery','Create a launch or delivery checklist, documentation requirements, handover steps, and rollback/backup considerations where relevant.']];html+='<div class="result-block"><div class="block-head"><h3>🤖 AI Prompt Chain</h3></div><div class="block-body">';prompts.forEach((p,i)=>{const pr=promptFor(p[0],p[1]);html+=`<div style="margin-bottom:18px"><div class="block-head"><h3>${i+1}. ${p[0]}</h3><button class="mini-btn copyPrompt" data-prompt="${encodeURIComponent(pr)}">Copy</button></div><div class="prompt-box">${escapeHtml(pr)}</div></div>`;text+=`PROMPT ${i+1} — ${p[0]}\n${pr}\n\n`;});html+='</div></div>';}
 if(checks.includes('checklist')||checks.includes('testing')){const items=['Project goal is clearly defined','Target user and use case are documented','Requirements are prioritized','Scope and assumptions are explicit','Project outputs are saved and organized','Each phase has been reviewed before moving forward','User experience / usability checked','Inputs are validated','Errors and edge cases tested','Security and privacy reviewed where relevant','Performance checked where relevant','Documentation completed'];html+=`<div class="result-block"><div class="block-head"><h3>✅ Project Checklist</h3></div><div class="block-body"><div class="check-list">${items.map(x=>`<div>☐ ${x}</div>`).join('')}</div></div></div>`;text+='CHECKLIST\n'+items.map(x=>'[ ] '+x).join('\n')+'\n\n';}
 if(checks.includes('deployment')){const content='Create a deployment or delivery plan for this project. Identify the target platform, required accounts, environment variables or configuration, build steps, backups, verification checks, monitoring, documentation, and rollback steps. Do not expose secrets.';html+=block('Deployment / Delivery Prompt',promptFor('',content),'');text+='DEPLOYMENT PROMPT\n'+promptFor('',content)+'\n\n';}
 $('#resultContent').innerHTML=html;state.resultText=text;$('#wizard').classList.add('hidden');$('#result').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});bindCopy();
}
function block(title,prompt){return `<div class="result-block"><div class="block-head"><h3>${title}</h3><button class="mini-btn copyPrompt" data-prompt="${encodeURIComponent(prompt)}">Copy</button></div><div class="block-body"><div class="prompt-box">${escapeHtml(prompt)}</div></div></div>`}
function escapeHtml(s){return s.replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function bindCopy(){$$('.copyPrompt').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(decodeURIComponent(b.dataset.prompt));const old=b.textContent;b.textContent='Copied ✓';setTimeout(()=>b.textContent=old,1200);});}
$('#categorySearch').oninput=e=>renderCategories(e.target.value);$('#startBtn').onclick=()=>{$('#wizard').scrollIntoView({behavior:'smooth'});};$('#nextBtn').onclick=()=>{if(!validate())return;if(state.step<4)goStep(state.step+1);else generate()};$('#prevBtn').onclick=()=>goStep(state.step-1);$('#projectName').oninput=updatePreview;$('#goal').oninput=updatePreview;$$('#levelChips button').forEach(b=>b.onclick=()=>{$$('#levelChips button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.level=b.dataset.value});$('#levelChips button').click();$('#copyAllBtn').onclick=async()=>{await navigator.clipboard.writeText(state.resultText);$('#copyAllBtn').textContent='Copied ✓';setTimeout(()=>$('#copyAllBtn').textContent='Copy All',1200)};$('#downloadBtn').onclick=()=>{const blob=new Blob([state.resultText],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai-project-copilot-'+($('#projectName').value||'project').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.txt';a.click();URL.revokeObjectURL(a.href)};$('#newBtn').onclick=()=>location.reload();$('#randomBtn').onclick=()=>{const c=CATEGORIES[Math.floor(Math.random()*CATEGORIES.length)];state.category=c;renderCategories();fillTypes();$('#projectName').value=`${PROJECT_TYPES[c[1]][0]} for ${c[1]}`;$('#goal').value=`Create a practical ${PROJECT_TYPES[c[1]][0].toLowerCase()} project related to ${c[1]}. Guide me from idea and requirements through execution, review, testing, and delivery.`;updatePreview();$('#wizard').scrollIntoView({behavior:'smooth'});};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('apc-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('apc-theme')==='dark')document.body.classList.add('dark');renderCategories();goStep(1);
